# Generated by Django 3.0 on 2019-12-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quanitiy',
        ),
    ]
