# Generated by Django 2.2 on 2020-01-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200113_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequestmodel',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
