# Generated by Django 2.2 on 2020-01-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200113_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_type',
            field=models.CharField(choices=[('D', 'Double'), ('S', 'Single'), ('C', 'Children'), ('O', 'Office'), ('CO', 'Computer'), ('CH', 'Chair_desk'), ('F', 'Floor'), ('CI', 'Cieling')], default='S', max_length=2),
        ),
    ]
