# Generated by Django 2.2 on 2020-01-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_itemmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttags',
            name='id',
        ),
        migrations.AlterField(
            model_name='producttags',
            name='tag_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.ItemModel'),
        ),
    ]
